name: Release And Update
on:
  workflow_dispatch:
    inputs:

jobs:
  apk:
    name: Release APK
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Java8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Generate APK
        run: ./gradlew build

      - name: List APK
        run: ls app/build/outputs/apk

      - name: Android Sign
        uses: Tlaster/android-sign@v1.2.2
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          output: build/release/signed
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "30.0.2"

      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: apk
          path: build/release/signed


