name: Release And Update
on:
  workflow_dispatch:
    inputs:

jobs:
  apk:
    name: Release APK
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Java8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Generate Debug APK
        run: ./gradlew build

      - uses: Tlaster/android-sign@v1
        name: Sign app APK
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          output: build/release/signed
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "30.0.2"

      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: apk
          path: app/build/outputs/apk/release

      - name: Create Release and Upload debug APK
        uses: underwindfall/create-release-with-debugapk@v1.2.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{GITHUB_RUN_ID}}
          release_name: Release v${{GITHUB_RUN_ID}}
          asset_path: app/build/outputs/apk/release/
          asset_name: *
          draft: false
          prerelease: false
